name: Build flutter release
"on":
  push:
    branches:
      - master
jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
    - run: flutter clean 
    - run: flutter pub get 
    - run: flutter build linux
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
    - run: flutter clean 
    - run: flutter pub get 
    - run: flutter build macos   
  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
        channel: 'stable'
    - run: flutter clean 
    - run: flutter pub get 
    - run: flutter build windows
      